services:
  backend:
    container_name: fastapi_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - my_project_network
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./app/.env
    environment:
      - PYTHONPATH=/app

  mongo:
    image: mongo:5.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - my_project_network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 3
      start_period: 5s

  redis:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - my_project_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 3
      start_period: 5s

networks:
  my_project_network:
    external: true

volumes:
  mongo_data: